//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emoji_picker_wpf {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("emoji_picker_wpf.resources", typeof(resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;😀&quot;: {
        ///    &quot;name&quot;: &quot;grinning face&quot;,
        ///    &quot;slug&quot;: &quot;grinning_face&quot;,
        ///    &quot;group&quot;: &quot;Smileys &amp; Emotion&quot;,
        ///    &quot;emoji_version&quot;: &quot;1.0&quot;,
        ///    &quot;unicode_version&quot;: &quot;1.0&quot;,
        ///    &quot;skin_tone_support&quot;: false
        ///  },
        ///  &quot;😃&quot;: {
        ///    &quot;name&quot;: &quot;grinning face with big eyes&quot;,
        ///    &quot;slug&quot;: &quot;grinning_face_with_big_eyes&quot;,
        ///    &quot;group&quot;: &quot;Smileys &amp; Emotion&quot;,
        ///    &quot;emoji_version&quot;: &quot;0.6&quot;,
        ///    &quot;unicode_version&quot;: &quot;0.6&quot;,
        ///    &quot;skin_tone_support&quot;: false
        ///  },
        ///  &quot;😄&quot;: {
        ///    &quot;name&quot;: &quot;grinning face with smiling eyes&quot;,
        ///    &quot;slug&quot;: &quot;grinning_face_with_s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dataByEmoji {
            get {
                return ResourceManager.GetString("dataByEmoji", resourceCulture);
            }
        }
    }
}
